#' Generates Latex Appendix
#'
#' Creates a LaTeX appendix of regression summaries and descriptive statistics.
#'   A directory containing all the relevant files
#'
#' @param models A list of models generated by \code{build} or \code{describe}.
#' dir Path to Latex file node where the appendix folder will be appended.
#'
#' @examples
#'
#' data('freeny')
#' mod <- lm(y ~ lag.quarterly.revenue + price.index + income.level +
#'             market.potential, data = freeny)
#' mod2 <- lm(y ~ lag.quarterly.revenue + price.index + income.level,
#'           data = freeny)
#'
#' tex1 <- build(mod, label='f1', silent=TRUE)
#' tex2 <- build(mod2, label='f2', silent=TRUE)
#' d <- paste(getwd(), 'rchitEx', sep='/')
#' append(list(tex1, tex2), d)
#' ## <-- Latex files outputted to dir --> ##
#'
#' @export

appendize <- function(models, dir) {
  if (dir.exists(paste(dir, '/appendix', sep=''))) {
    stop('Directory already exists. Delete directory before creating new appendix.')
  }
  dir.create(paste(dir, '/appendix', sep=''))

  in_graph <- function(lbl, cap, file, options) {
    if (options$landscape) lndsp <- c('\\begin{landscape}' ,'\\end{landscape}')
    else lndsp <- c('','')

    paste(lndsp[1], '\n',
          '\\begin{table}[!htb]\n',
          '\t\\centering\n',
          '\t\\caption{', cap, '}\n',
          '\t\\label{', lbl, '}\n',
          '\t\\input{', file, '}\n',
          '\\end{table}\n',
          lndsp[2], '\n',
          '\\clearpage\n',
          sep = '')
  }

  in_plot <- function(plot) {
    #if (options$landscape) lndsp <- c('\\begin{landscape}' ,'\\end{landscape}')
    #else lndsp <- c('','')
    paste('\\begin{figure}[!htb]\n',
          '\t\\centering\n',
          '\t\\caption{', cap, '}\n',
          '\t\\label{', lbl, '}\n',
          '\t\\includegraphics[scale=1]{', file, '}\n',
          '\\end{figure}\n',
          '\\clearpage\n',
          sep = '')
  }


  appendix <- paste('\\section{Appendix}\n',
                    sep='\n')

  # creates tex code in appendix.tex
  out <- unlist(lapply(models, function(m) {
    if (class(m) == "g" || class(m) == 'ggplot') {
      in_plot(m)

    } else {
      in_graph(m$label, m$caption, paste(dir, '/appendix/', m$label, '.tex', sep=''), m$options)
    }
    }))
  out <- paste(out, sep='\n')
  appendix <- c(appendix, out)
  writeLines(appendix, con = paste(dir, '/appendix/appendix.tex', sep=''))

  # saves the individual models
  for (mod in models) {
    writeLines(mod$tex, con = paste(dir, '/appendix/', mod$label, '.tex', sep=''))
  }

}
